'use strict';
const $=id=>document.getElementById(id);
const lessons=[
{title:'Primeiros passos em Python',tag:'PROGRAMAÇÃO',text:'Python é uma linguagem de programação de propósito geral, criada por Guido van Rossum e lançada em 1991. É usada em automação, sites, ciência de dados e outras áreas. Não foi criada especificamente para celulares.\n\nSeu primeiro programa:\nprint("Olá, mundo!")\n\nprint é uma função que mostra informações. As aspas delimitam um texto, chamado string.\n\nExperimente: escreva uma linha que mostre seu nome. Depois, explique o papel de cada símbolo.\n\nReferência: tutorial oficial do Python — docs.python.org/pt-br/3/tutorial/'},
{title:'Listas: uma coleção de ideias',tag:'PYTHON',text:'Uma lista guarda vários valores em uma sequência.\n\nfrutas = ["maçã", "banana"]\n\nfrutas é o nome da variável. O sinal = atribui a lista à variável. Colchetes delimitam a lista; vírgulas separam os elementos.\n\nprint(frutas[0])\n\nMostra maçã: em Python, o primeiro índice é 0.\n\nfrutas.append("uva")\n\nAcrescenta uva ao final.\n\nDesafio: crie uma lista com três jogos e mostre o segundo. Qual índice você usará?\n\nReferência: docs.python.org/pt-br/3/tutorial/introduction.html#lists'},
{title:'Frações no cotidiano',tag:'MATEMÁTICA',text:'Uma fração representa uma relação entre números. Ao dividir um bolo em 4 partes iguais e pegar 1, você pega 1/4 do bolo.\n\nO denominador indica em quantas partes iguais o inteiro foi dividido. O numerador indica quantas dessas partes estamos considerando.\n\n1/4 + 2/4 = 3/4\n\nCom denominadores diferentes, precisamos representar as frações com um denominador comum:\n1/2 + 1/4 = 2/4 + 1/4 = 3/4.\n\nDesafio: você bebeu 1/3 de uma garrafa de manhã e 1/3 à tarde. Que fração restou?'},
{title:'Ler, interpretar e verificar',tag:'LINGUAGENS',text:'Antes de aceitar uma informação, observe quem a escreveu, quando foi publicada e quais evidências apresenta.\n\nFato: uma afirmação que pode ser verificada.\nOpinião: um julgamento ou ponto de vista.\nInferência: uma conclusão construída a partir de pistas.\n\nAo ler, pergunte: qual é o tema? Qual ideia o autor defende? Que trecho sustenta minha interpretação?\n\nAtividade: escolha uma notícia e separe uma afirmação verificável de uma opinião. Procure uma segunda fonte independente.'},
{title:'Como estudar com uma IA',tag:'APRENDER A APRENDER',text:'Use a IA para pedir explicações, exemplos e perguntas de prática. Conte o que você já entendeu antes de pedir ajuda.\n\nUm bom pedido: "Estou aprendendo listas em Python. Explique o índice 0 e depois me dê um exercício, sem mostrar a resposta."\n\nModelos podem produzir informações incorretas com muita confiança. Compare a resposta com seu livro, material da aula ou documentação oficial.\n\nEscreva no caderno uma explicação com suas palavras. Se não conseguir, identifique a parte que ainda precisa estudar.'},
{title:'Internet e funcionamento offline',tag:'TECNOLOGIA',text:'Um site usa arquivos como HTML, CSS e JavaScript. Um servidor entrega esses arquivos ao navegador.\n\nUma PWA pode guardar arquivos no dispositivo usando um service worker. Depois do primeiro carregamento completo, os recursos armazenados podem funcionar sem internet.\n\nNeste NOMAD, a biblioteca e o caderno funcionam offline. Nesta PWA, o chat usa WebLLM e um modelo MLC baixado no navegador.\n\nSem um modelo carregado, a biblioteca e o caderno continuam disponíveis.'}
];
let storageOK=true;function read(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{storageOK=false;$('status').textContent='Armazenamento indisponível';return false}}
let history=read('nomad.pwa.history',[]);if(!Array.isArray(history))history=[];history=history.filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').slice(-100);
let busy=false, requestId=0, pending=null;
function nativeStatus(){try{return JSON.parse(NomadNative.getStatus())}catch{return {ready:false,message:'Motor indisponível.'}}}
function health(){const d=nativeStatus();$('status').textContent=d.ready?'IA local · offline':'Modelo não carregado';$('modelStatus').textContent=d.message;$('modelInfo').textContent=d.model||'Nenhum modelo carregado.';$('wikiStatus').textContent=d.wiki||'Selecione o arquivo ZIM.';$('importModel').disabled=d.busy;}
window.addEventListener('nomad-status',health);
$('importModel').onclick=()=>NomadNative.importModel();
$('openWiki').onclick=()=>NomadNative.openWikipedia();
function message(role,text,error=false){const el=document.createElement('div');el.className='message '+role+(error?' error':'');const label=document.createElement('strong');label.textContent=role==='user'?'VOCÊ':'NOMAD';const content=document.createElement('div');content.textContent=text;el.append(label,content);$('messages').append(el);el.scrollIntoView({block:'nearest'});return content}
function typingMessage(){const el=message('assistant','');el.classList.add('typing-indicator');el.setAttribute('role','status');el.setAttribute('aria-label','NOMAD está digitando');el.innerHTML='<span>NOMAD está digitando</span><span class="typing-dots" aria-hidden="true"><i></i><i></i><i></i></span>';return el}
function render(){ $('messages').replaceChildren();if(history.length){history.forEach(m=>message(m.role,m.content));return}const box=document.createElement('div');box.className='welcome';box.innerHTML='<small>SEU COMPANHEIRO DE ESTUDOS</small><h2>O mundo é grande.<br>Sua curiosidade também.</h2><p>Faça uma pergunta ou explore os guias da biblioteca.</p><div class="chips"></div>';['Me ensine listas em Python','Como somar frações?','Ajude-me a estudar um texto'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{$('input').value=t;$('input').focus()};box.querySelector('.chips').append(b)});$('messages').append(box)}
function view(id){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('title').textContent={chat:'Conversar',library:'Biblioteca',notes:'Meu caderno',settings:'Modelo',wikipedia:'Wikipédia'}[id]}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('form').onsubmit=e=>{
 e.preventDefault();const text=$('input').value.trim();if(!text||busy)return;
 if(!nativeStatus().ready){view('settings');health();return;}
 busy=true;$('send').disabled=true;$('stop').hidden=false;
 history.push({role:'user',content:text});history=history.slice(-100);save('nomad.pwa.history',history);render();$('input').value='';
 pending={id:String(++requestId),answer:typingMessage()};
 NomadNative.chat(pending.id,JSON.stringify(history.slice(-12)));
};
window.addEventListener('nomad-result',e=>{
 const d=e.detail;if(!pending||d.id!==pending.id)return;
 pending.answer.classList.remove('typing-indicator');pending.answer.removeAttribute('aria-label');
 if(d.error){pending.answer.textContent=d.error;pending.answer.parentElement.classList.add('error');}
 else{pending.answer.textContent=d.content;history.push({role:'assistant',content:d.content});save('nomad.pwa.history',history.slice(-100));}
 busy=false;pending=null;$('send').disabled=false;$('stop').hidden=true;health();
});
$('stop').onclick=()=>{NomadNative.cancel();if(pending)pending.answer.textContent='Interrompendo…';};
$('newChat').onclick=()=>{if(busy)return;if(history.length&&!confirm('Limpar a conversa salva neste dispositivo?'))return;history=[];save('nomad.pwa.history',history);render()};
function download(name,text){if(window.NomadNative){window.NomadNative.exportText(name,text);return}const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>download('nomad-conversa.txt',history.map(m=>(m.role==='user'?'VOCÊ':'NOMAD')+':\n'+m.content).join('\n\n'));
$('notepad').value=read('nomad.pwa.notes','');$('notepad').oninput=()=>{$('noteStatus').textContent=save('nomad.pwa.notes',$('notepad').value)?'Notas salvas neste dispositivo.':'Não foi possível salvar. Exporte suas notas.'};$('exportNotes').onclick=()=>download('nomad-notas.txt',$('notepad').value);
function cards(){const q=$('search').value.toLocaleLowerCase('pt-BR');$('cards').replaceChildren();lessons.filter(l=>(l.title+' '+l.text).toLocaleLowerCase('pt-BR').includes(q)).forEach(l=>{const b=document.createElement('button');b.className='card';const s=document.createElement('small');s.textContent=l.tag;const t=document.createElement('strong');t.textContent=l.title;b.append(s,t);b.onclick=()=>{$('lesson').replaceChildren();const h=document.createElement('h2');h.textContent=l.title;const p=document.createElement('div');p.textContent=l.text;$('lesson').append(h,p);$('lesson').hidden=false;$('lesson').scrollIntoView({behavior:'smooth'})};$('cards').append(b)});if(!$('cards').children.length)$('cards').textContent='Nenhum guia encontrado.'}$('search').oninput=cards;
window.addEventListener('nomad-chunk',e=>{const d=e.detail;if(!pending||d.id!==pending.id)return;pending.answer.classList.remove('typing-indicator');pending.answer.removeAttribute('aria-label');pending.answer.textContent=d.content;});
render();cards();health();
